################################### Default Configuration ############################
baseURL = "https://marcofsilva.github.io/Meltek3D_Website/"
defaultContentLanguage = "pt"
disableLanguages = []
googleAnalytics = ""
summarylength = "20"
theme = "vex-hugo"
title = "Meltek3D"

#################################### Geral - Menu #####################################
[[menu.social]]
URL    = "https://www.facebook.com/"
name   = "Facebook"
icon   = ""
weight = 1
[[menu.social]]
URL    = "https://www.instagram.com/"
name   = "Instagram"
icon   = ""
weight = 2
[[menu.social]]
URL    = "https://www.linkedin.com/"
name   = "Linkedin"
icon   = ""
weight = 3

#################################### Languages - Menu #################################
# English
[Languages.en]
contentDir = "content/english"
copyright = "Copyright © {now_year} Meltek3D"
languageCode = "en-us"
languageName = "En"
weight = 1
#[[Languages.en.menu.footer]]
#URL = "blog"
#name = "Blog"
#weight = 1
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 2
[[Languages.en.menu.footer]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 3
[[Languages.en.menu.footer]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 4
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "products"
name = "Products"
weight = 2
#[[Languages.en.menu.main]]
#URL = "blog"
#name = "Blog"
#weight = 3
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 4

# Portuguese
[Languages.pt]
contentDir = "content/portuguese"
copyright = "Copyright © {now_year} Meltek3D"
languageCode = "pt-pt"
languageName = "Pt"
weight = 2
#[[Languages.pt.menu.footer]]
#URL = "blog"
#name = "Blog"
#weight = 1
[[Languages.pt.menu.footer]]
URL = "contact"
name = "Contactos"
weight = 2
[[Languages.pt.menu.footer]]
URL = "terms-conditions"
name = "Termos & Condições"
weight = 3
[[Languages.pt.menu.footer]]
URL = "privacy-policy"
name = "Política de Privacidade"
weight = 4
[[Languages.pt.menu.main]]
URL = "/"
name = "Página Inicial"
weight = 1
[[Languages.pt.menu.main]]
URL = "products"
name = "Produtos"
weight = 2
#[[Languages.pt.menu.main]]
#URL = "blog"
#name = "Blog"
#weight = 3
[[Languages.pt.menu.main]]
URL = "contact"
name = "Contactos"
weight = 4

#################################### Plugins ##########################################
# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"

[params.preloader]
enable = true
preloader = ""

[params.subscription]
#XXXmailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
#XXXmailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

#################################### Default Params ####################################
[params]
author              = "Marco Silva"
contact_form_action = "#"
currency            = "€"
description         = "This is meta description"
logo_header         = "images/meltek3d_logo_left.png"
logo_header_width   = "170px"
logo                = "images/meltek3d_logo_up.png"
logo_width          = "120px"
enable_cart         = false
#XXX snipcart_api        = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"