---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: images
  type: image_gallery
  config: {}
  label: images
- type: text
  name: gallery_buy/info/description
  label: description
  config:
    required: true
- type: text
  name: price
  label: price
- type: text
  name: discount_price
  label: discount_price
- type: list
  name: colors
  label: colors
- type: list
  name: sizes
  label: sizes
