---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  default: now
  config:
    date_format: DD/MM/YYYY
- name: images
  type: image_gallery
  config: {}
  label: images
- name: gallery_buy
  type: field_group
  config: {}
  fields:
  - name: enable
    type: boolean
    label: Enable
    hidden: true
    default: true
  - name: price
    type: text
    config:
      required: true
    label: Price
  - name: discount_price
    type: text
    config:
      required: false
    label: Discount Price
    description: Preço atual com desconto.
  - name: price_personalized
    type: text
    config:
      required: false
    label: Price Personalized
    description: "( € personalizado com nome )"
  - name: colors
    type: list
    config:
      use_select: false
      min: 1
      max: 
    label: Colors
  - name: size
    type: number
    label: Size
    description: 'Tamanho: número de cápsulas, frascos, etc.<br>Deixar vazio caso
      não seja necessário referir tamanho nenhum.'
    default: 
    required: true
    config:
      min: 1
      max: 
      step: 1
  - name: other_sizes
    type: list
    config:
      use_select: false
      min: 
      max: 
    label: Other Sizes
    description: Outros tamanhos disponíveis
  - name: info
    type: field_group
    config: {}
    fields:
    - name: description
      type: text
      config:
        required: true
      label: Description
    - name: material
      type: textarea
      default: ''
      config:
        required: false
        wysiwyg: false
        schema:
          format: markdown
      label: Material
    - name: dimensions
      type: textarea
      default: ''
      config:
        required: false
        wysiwyg: false
        schema:
          format: markdown
      label: Dimensions
    - name: extras
      type: textarea
      default: ''
      config:
        required: false
        wysiwyg: false
        schema:
          format: markdown
      label: Extras
    label: Info Descritiva
  label: Gallery Buy
  description: Informação referente ao produto, tal como preço, descrição, etc.
- name: features
  type: field_group
  config: {}
  fields:
  - name: enable
    type: boolean
    label: Enable
    default: false
  label: Features
  description: Zona mais descritiva sobre o produto. Ainda não estandardizado.
  hidden: true
- name: other_products
  type: field_group
  config: {}
  fields:
  - name: enable
    type: boolean
    label: Enable
    default: true
  label: Other Products
  description: Secção no final da página a mostrar outros produtos.
